/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import Controller.PasswordGenerator;

/**
 *
 * @author Asus
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    private int xPoint = 0;
    private int yPoint = 0;
    private PasswordGenerator passGen;
    private boolean aboutPageOpen = false;
    private aboutProgram abPr = new aboutProgram();
    
    public MainGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        jRadioButtonNo.setSelected(true);
    }
    
    public MainGUI(String generatedPassword) {
        initComponents();
        this.setLocationRelativeTo(null);
        jRadioButtonNo.setSelected(true);
        jTextFieldPassword.setText(generatedPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        topTitleBar = new javax.swing.JPanel();
        closeWindowPanel = new javax.swing.JPanel();
        closeWindowButton = new javax.swing.JLabel();
        windowTitle = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jLabelLength = new javax.swing.JLabel();
        jLabelSpecialChar = new javax.swing.JLabel();
        jComboBoxLength = new javax.swing.JComboBox<>();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jButtonGenerate = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelAbout = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Password Generator v1.1");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topTitleBar.setBackground(new java.awt.Color(102, 0, 204));
        topTitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topTitleBarMouseDragged(evt);
            }
        });
        topTitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topTitleBarMousePressed(evt);
            }
        });

        closeWindowPanel.setBackground(new java.awt.Color(102, 0, 102));

        closeWindowButton.setBackground(new java.awt.Color(0, 153, 153));
        closeWindowButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        closeWindowButton.setForeground(new java.awt.Color(255, 255, 255));
        closeWindowButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeWindowButton.setText("X");
        closeWindowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closeWindowPanelLayout = new javax.swing.GroupLayout(closeWindowPanel);
        closeWindowPanel.setLayout(closeWindowPanelLayout);
        closeWindowPanelLayout.setHorizontalGroup(
            closeWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeWindowPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(closeWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        closeWindowPanelLayout.setVerticalGroup(
            closeWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        windowTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        windowTitle.setForeground(new java.awt.Color(255, 255, 255));
        windowTitle.setText("Simple Password Generator");

        javax.swing.GroupLayout topTitleBarLayout = new javax.swing.GroupLayout(topTitleBar);
        topTitleBar.setLayout(topTitleBarLayout);
        topTitleBarLayout.setHorizontalGroup(
            topTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topTitleBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(windowTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(closeWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topTitleBarLayout.setVerticalGroup(
            topTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topTitleBarLayout.createSequentialGroup()
                .addComponent(closeWindowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
            .addGroup(topTitleBarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(windowTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(topTitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 80));

        contentPanel.setBackground(new java.awt.Color(102, 102, 102));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLength.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLength.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLength.setText("Length:");
        contentPanel.add(jLabelLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 94, -1, -1));

        jLabelSpecialChar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSpecialChar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSpecialChar.setText("Special Character:");
        contentPanel.add(jLabelSpecialChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 135, -1, -1));

        jComboBoxLength.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 Characters (Default)", "9 Characters", "10 Characters", "11 Characters", "12 Characters", "13 Characters", "14 Characters", "15 Characters", "16 Characters" }));
        contentPanel.add(jComboBoxLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 92, 205, -1));
        contentPanel.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 52, 205, -1));

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password:");
        contentPanel.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 54, -1, -1));

        jRadioButtonYes.setBackground(new java.awt.Color(102, 102, 102));
        jbuttonGroup.add(jRadioButtonYes);
        jRadioButtonYes.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonYes.setText("Yes");
        jRadioButtonYes.setActionCommand("yes");
        contentPanel.add(jRadioButtonYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 132, -1, -1));

        jRadioButtonNo.setBackground(new java.awt.Color(102, 102, 102));
        jbuttonGroup.add(jRadioButtonNo);
        jRadioButtonNo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNo.setText("No");
        jRadioButtonNo.setActionCommand("no");
        contentPanel.add(jRadioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 132, -1, -1));

        jButtonGenerate.setBackground(new java.awt.Color(204, 255, 255));
        jButtonGenerate.setText("Generate");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });
        contentPanel.add(jButtonGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jButtonClear.setBackground(new java.awt.Color(255, 153, 153));
        jButtonClear.setText("Clear");
        jButtonClear.setActionCommand("");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        contentPanel.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 88, -1));

        jLabelAbout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAbout.setForeground(new java.awt.Color(255, 255, 0));
        jLabelAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAbout.setText("?");
        jLabelAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAboutMouseClicked(evt);
            }
        });
        contentPanel.add(jLabelAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 28, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Copy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 52, -1, 22));

        jPanel1.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 620, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeWindowButtonMouseClicked

    private void topTitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topTitleBarMousePressed
        xPoint = evt.getX();
        yPoint = evt.getY();
    }//GEN-LAST:event_topTitleBarMousePressed

    private void topTitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topTitleBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xPoint, y-yPoint);
    }//GEN-LAST:event_topTitleBarMouseDragged

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldPassword.setText("");
        jRadioButtonNo.setSelected(true);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
        passGen = new PasswordGenerator();
        int passLength = 0;
        
        passLength = getSelectedPassLength();
        
        if(jbuttonGroup.getSelection().getActionCommand().equals("yes"))
        {
            passGen.generatetPasswordSpecial(passLength);
            jTextFieldPassword.setText(passGen.getGeneratedPassword());
        }
        
        else
        {
            passGen.generatetPasswordNormal(passLength);
            jTextFieldPassword.setText(passGen.getGeneratedPassword());
        }
    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jLabelAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAboutMouseClicked
        if(abPr.isVisible() == false)
        {
            abPr.setVisible(true);
        }
        else{}
    }//GEN-LAST:event_jLabelAboutMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        copyToClipboardButton();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    public int getSelectedPassLength()
    {
        if(Integer.parseInt(String.valueOf(jComboBoxLength.getSelectedIndex())) == 0)
        {
            return 8;
        }
        
        else if(Integer.parseInt(String.valueOf(jComboBoxLength.getSelectedIndex())) == 1)
        {
            return 9;
        }
        
        else if(Integer.parseInt(String.valueOf(jComboBoxLength.getSelectedIndex())) == 2)
        {
            return 10;
        }
        
        else if(Integer.parseInt(String.valueOf(jComboBoxLength.getSelectedIndex())) == 3)
        {
            return 11;
        }
        
        else if(Integer.parseInt(String.valueOf(jComboBoxLength.getSelectedIndex())) == 4)
        {
            return 12;
        }
        
        else if(Integer.parseInt(String.valueOf(jComboBoxLength.getSelectedIndex())) == 5)
        {
            return 13;
        }
        
        else if(Integer.parseInt(String.valueOf(jComboBoxLength.getSelectedIndex())) == 6)
        {
            return 14;
        }
        
        else if(Integer.parseInt(String.valueOf(jComboBoxLength.getSelectedIndex())) == 7)
        {
            return 15;
        }
        
        else{return 16;}
    }
    
    public void copyToClipboardButton()
    {
        String generatedPassword = "";
        
        generatedPassword = jTextFieldPassword.getText();
        
        Toolkit toolKit = Toolkit.getDefaultToolkit();
        Clipboard clipBoard = toolKit.getSystemClipboard();
        StringSelection strSel = new StringSelection(generatedPassword);
        clipBoard.setContents(strSel, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeWindowButton;
    private javax.swing.JPanel closeWindowPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JComboBox<String> jComboBoxLength;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelLength;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSpecialChar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.ButtonGroup jbuttonGroup;
    private javax.swing.JPanel topTitleBar;
    private javax.swing.JLabel windowTitle;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
